[config]

[templates.vencord]
input_path = "/home/key/.config/matugen/templates/midnight-discord.css"
output_path = "/home/key/.config/Vencord/themes/midnight-discord.css"

[templates.pywalfox]
input_path = '/home/key/.config/matugen/templates/pywalfox-colors.json'
output_path = '~/.cache/wal/colors.json'
post_hook = "pywalfox update"

[templates.micro]
input_path = '/home/key/.config/matugen/templates/micro.micro'
output_path = '/home/key/.config/micro/colorschemes'